databases:
  - name: proyecto_inmuebles 
    plan: free
    databaseName: proyecto_inmuebles
    user: mysuperusuario

services:
  - type: web
    plan: free
    name: proyecto_inmuebles
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn proyecto_inmuebles.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: proyecto_inmuebles
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
